template = "https://github.com/giellalt/template-lang-und"
rev_id = 323
template_sha = "dfd6613f16d25eef74b592360a48496624ab327d"

[replacements]
__GLOTTOLOG_ID__ = "inap1242"
__LICENCE__ = "GPLv3"
__REPO__ = "lang-inp"
__UND2C__ = "inp"
__UNDEFINED__ = "Iñapari"
__UND__ = "inp"
