template = "https://github.com/giellalt/template-lang-und"
rev_id = 326
template_sha = "f8bbffe1f3b8a6dd1aca7238f0aa238554081b55"

[replacements]
__GLOTTOLOG_ID__ = "inap1242"
__LICENCE__ = "GPLv3"
__REPO__ = "lang-inp"
__UND2C__ = "inp"
__UNDEFINED__ = "Iñapari"
__UND__ = "inp"
