template = "https://github.com/giellalt/template-lang-und"
rev_id = 283
template_sha = "bfef967c632b9041975725ec13da8c2dfe66b74e"

[replacements]
__GLOTTOLOG_ID__ = "inap1242"
__LICENCE__ = "GPLv3"
__REPO__ = "lang-inp"
__UND2C__ = "inp"
__UNDEFINED__ = "Iñapari"
__UND__ = "inp"
